shooting-stars-per-minute: 3
falling-stars-per-minute: 0.2
falling-stars-radius: 75
falling-stars-spark-time: 200
falling-stars-experience: 100
falling-stars-loot:
  nether_star: 0.1
  diamond: 60
  emerald: 20
  fire_charge: 10
  blaze_powder: 10