name: Celeste
version: 1.3
api-version: 1.14
author: Idrees
main: com.idreesinc.celeste.Celeste

commands:
  shootingstar:
    description: Creates a shooting star near the player that summons it, or optionally near another player
    usage: /<command> [player]
    permission: celeste.shootingstar
  fallingstar:
    description: Creates a falling star near the player that summons it, or optionally near another player
    usage: /<command> [player]
    permission: celeste.fallingstar
