name: Celeste
version: 1.0
api-version: 1.14
author: Idrees
main: com.idreesinc.celeste.Celeste

commands:
  star:
    description: Creates a falling star near the player that summons it
    usage: /<command>
    permission: celeste.star